M48
; DRILL file {KiCad (6.0.4)} date Fri May 20 17:11:02 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-05-20T17:11:02-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.4)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X106.893Y-105.201
X177.962Y-63.6
X198.13Y-137.002
T0
M30
